// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sad.Api.Data;

#nullable disable

namespace SADWebApi.Migrations
{
    [DbContext(typeof(SadDbContext))]
    [Migration("20251228052715_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sad.Api.Data.Entities.AuthUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Users_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users", "auth");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.AuthUserExternalLogin", b =>
                {
                    b.Property<long>("UserExternalLoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserExternalLoginId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<byte>("IdentityProviderId")
                        .HasColumnType("tinyint");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserExternalLoginId");

                    b.HasIndex("UserId");

                    b.HasIndex("IdentityProviderId", "ProviderSubject")
                        .IsUnique();

                    b.ToTable("UserExternalLogins", "auth");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.CatalogCreditCardProduct", b =>
                {
                    b.Property<int>("CreditCardProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CreditCardProductId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CreditCardProductId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("CreditCardProducts", "catalog");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.CatalogIdentityProvider", b =>
                {
                    b.Property<byte>("IdentityProviderId")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdentityProviderId");

                    b.HasIndex("ProviderCode")
                        .IsUnique();

                    b.ToTable("IdentityProviders", "catalog");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.CatalogMembershipProduct", b =>
                {
                    b.Property<int>("MembershipProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembershipProductId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MembershipProductId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("MembershipProducts", "catalog");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.CatalogSaleStatus", b =>
                {
                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("bit");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("SaleStatus", "catalog");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.CatalogStore", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StoreName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoreNumber")
                        .HasColumnType("int");

                    b.HasKey("StoreId");

                    b.HasIndex("StoreNumber")
                        .IsUnique();

                    b.ToTable("Stores", "catalog");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.SalesCreditCardApplication", b =>
                {
                    b.Property<long>("CreditCardApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CreditCardApplicationId"));

                    b.Property<int>("CreditCardProductId")
                        .HasColumnType("int");

                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CreditCardApplicationId");

                    b.HasIndex("CreditCardProductId");

                    b.HasIndex("StatusId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("CreditCardApplications", "sales");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.SalesMembershipSale", b =>
                {
                    b.Property<long>("MembershipSaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MembershipSaleId"));

                    b.Property<int>("MembershipProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SoldAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MembershipSaleId");

                    b.HasIndex("MembershipProductId");

                    b.HasIndex("StatusId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("MembershipSales", "sales");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.AuthUserExternalLogin", b =>
                {
                    b.HasOne("Sad.Api.Data.Entities.CatalogIdentityProvider", "IdentityProvider")
                        .WithMany("UserExternalLogins")
                        .HasForeignKey("IdentityProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sad.Api.Data.Entities.AuthUser", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.SalesCreditCardApplication", b =>
                {
                    b.HasOne("Sad.Api.Data.Entities.CatalogCreditCardProduct", "CreditCardProduct")
                        .WithMany()
                        .HasForeignKey("CreditCardProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sad.Api.Data.Entities.CatalogSaleStatus", "Status")
                        .WithMany("CreditCardApplications")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sad.Api.Data.Entities.CatalogStore", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sad.Api.Data.Entities.AuthUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCardProduct");

                    b.Navigation("Status");

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.SalesMembershipSale", b =>
                {
                    b.HasOne("Sad.Api.Data.Entities.CatalogMembershipProduct", "MembershipProduct")
                        .WithMany()
                        .HasForeignKey("MembershipProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sad.Api.Data.Entities.CatalogSaleStatus", "Status")
                        .WithMany("MembershipSales")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sad.Api.Data.Entities.CatalogStore", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sad.Api.Data.Entities.AuthUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipProduct");

                    b.Navigation("Status");

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.AuthUser", b =>
                {
                    b.Navigation("ExternalLogins");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.CatalogIdentityProvider", b =>
                {
                    b.Navigation("UserExternalLogins");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.CatalogSaleStatus", b =>
                {
                    b.Navigation("CreditCardApplications");

                    b.Navigation("MembershipSales");
                });
#pragma warning restore 612, 618
        }
    }
}
