// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sad.Api.Data;

#nullable disable

namespace SADWebApi.Migrations
{
    [DbContext(typeof(SadDbContext))]
    partial class SadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SADWebApi.Data.Entities.CatalogUserDailySetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppsGoal")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MembershipsGoal")
                        .HasColumnType("integer");

                    b.Property<decimal>("SalesGoalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("SettingDate")
                        .HasColumnType("date");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId", "SettingDate")
                        .IsUnique();

                    b.ToTable("UserDailySettings", "catalog");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.AuthUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Anumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<int?>("StoreId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Users_Email")
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.ToTable("Users", "auth");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.AuthUserExternalLogin", b =>
                {
                    b.Property<long>("UserExternalLoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserExternalLoginId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<byte>("IdentityProviderId")
                        .HasColumnType("smallint");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserExternalLoginId");

                    b.HasIndex("UserId");

                    b.HasIndex("IdentityProviderId", "ProviderSubject")
                        .IsUnique();

                    b.ToTable("UserExternalLogins", "auth");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.CatalogCreditCardProduct", b =>
                {
                    b.Property<int>("CreditCardProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CreditCardProductId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CreditCardProductId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("CreditCardProducts", "catalog");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.CatalogIdentityProvider", b =>
                {
                    b.Property<byte>("IdentityProviderId")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdentityProviderId");

                    b.HasIndex("ProviderCode")
                        .IsUnique();

                    b.ToTable("IdentityProviders", "catalog");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.CatalogMembershipProduct", b =>
                {
                    b.Property<int>("MembershipProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MembershipProductId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MembershipProductId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("MembershipProducts", "catalog");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.CatalogSaleStatus", b =>
                {
                    b.Property<byte>("StatusId")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("StatusId");

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("SaleStatus", "catalog");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.CatalogStore", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoreId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("StoreName")
                        .HasColumnType("text");

                    b.Property<int>("StoreNumber")
                        .HasColumnType("integer");

                    b.HasKey("StoreId");

                    b.HasIndex("StoreNumber")
                        .IsUnique();

                    b.ToTable("Stores", "catalog");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.Sales.Sale", b =>
                {
                    b.Property<Guid>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("Tax")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SaleId");

                    b.HasIndex("StoreId", "SaleDate");

                    b.HasIndex("UserId", "SaleDate");

                    b.ToTable("Sales", "sales");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.SalesCreditCardApplication", b =>
                {
                    b.Property<long>("CreditCardApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CreditCardApplicationId"));

                    b.Property<int>("CreditCardProductId")
                        .HasColumnType("integer");

                    b.Property<byte>("StatusId")
                        .HasColumnType("smallint");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CreditCardApplicationId");

                    b.HasIndex("CreditCardProductId");

                    b.HasIndex("StatusId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("CreditCardApplications", "sales");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.SalesMembershipSale", b =>
                {
                    b.Property<long>("MembershipSaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MembershipSaleId"));

                    b.Property<int>("MembershipProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SoldAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<byte>("StatusId")
                        .HasColumnType("smallint");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("MembershipSaleId");

                    b.HasIndex("MembershipProductId");

                    b.HasIndex("StatusId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("MembershipSales", "sales");
                });

            modelBuilder.Entity("SADWebApi.Data.Entities.CatalogUserDailySetting", b =>
                {
                    b.HasOne("Sad.Api.Data.Entities.CatalogStore", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sad.Api.Data.Entities.AuthUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.AuthUserExternalLogin", b =>
                {
                    b.HasOne("Sad.Api.Data.Entities.CatalogIdentityProvider", "IdentityProvider")
                        .WithMany("UserExternalLogins")
                        .HasForeignKey("IdentityProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sad.Api.Data.Entities.AuthUser", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.SalesCreditCardApplication", b =>
                {
                    b.HasOne("Sad.Api.Data.Entities.CatalogCreditCardProduct", "CreditCardProduct")
                        .WithMany()
                        .HasForeignKey("CreditCardProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sad.Api.Data.Entities.CatalogSaleStatus", "Status")
                        .WithMany("CreditCardApplications")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sad.Api.Data.Entities.CatalogStore", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sad.Api.Data.Entities.AuthUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCardProduct");

                    b.Navigation("Status");

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.SalesMembershipSale", b =>
                {
                    b.HasOne("Sad.Api.Data.Entities.CatalogMembershipProduct", "MembershipProduct")
                        .WithMany()
                        .HasForeignKey("MembershipProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sad.Api.Data.Entities.CatalogSaleStatus", "Status")
                        .WithMany("MembershipSales")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sad.Api.Data.Entities.CatalogStore", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sad.Api.Data.Entities.AuthUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipProduct");

                    b.Navigation("Status");

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.AuthUser", b =>
                {
                    b.Navigation("ExternalLogins");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.CatalogIdentityProvider", b =>
                {
                    b.Navigation("UserExternalLogins");
                });

            modelBuilder.Entity("Sad.Api.Data.Entities.CatalogSaleStatus", b =>
                {
                    b.Navigation("CreditCardApplications");

                    b.Navigation("MembershipSales");
                });
#pragma warning restore 612, 618
        }
    }
}
